package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BankbranchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankbranchAllPropertiesEquals(Bankbranch expected, Bankbranch actual) {
        assertBankbranchAutoGeneratedPropertiesEquals(expected, actual);
        assertBankbranchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankbranchAllUpdatablePropertiesEquals(Bankbranch expected, Bankbranch actual) {
        assertBankbranchUpdatableFieldsEquals(expected, actual);
        assertBankbranchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankbranchAutoGeneratedPropertiesEquals(Bankbranch expected, Bankbranch actual) {
        assertThat(actual)
            .as("Verify Bankbranch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankbranchUpdatableFieldsEquals(Bankbranch expected, Bankbranch actual) {
        assertThat(actual)
            .as("Verify Bankbranch relevant properties")
            .satisfies(a -> assertThat(a.getBankcode()).as("check bankcode").isEqualTo(expected.getBankcode()))
            .satisfies(a -> assertThat(a.getBranchcode()).as("check branchcode").isEqualTo(expected.getBranchcode()))
            .satisfies(a -> assertThat(a.getBranchname()).as("check branchname").isEqualTo(expected.getBranchname()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankbranchUpdatableRelationshipsEquals(Bankbranch expected, Bankbranch actual) {
        // empty method
    }
}
