package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmpFunctionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpFunctionsAllPropertiesEquals(EmpFunctions expected, EmpFunctions actual) {
        assertEmpFunctionsAutoGeneratedPropertiesEquals(expected, actual);
        assertEmpFunctionsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpFunctionsAllUpdatablePropertiesEquals(EmpFunctions expected, EmpFunctions actual) {
        assertEmpFunctionsUpdatableFieldsEquals(expected, actual);
        assertEmpFunctionsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpFunctionsAutoGeneratedPropertiesEquals(EmpFunctions expected, EmpFunctions actual) {
        assertThat(actual)
            .as("Verify EmpFunctions auto generated properties")
            .satisfies(a -> assertThat(a.getFunctionId()).as("check functionId").isEqualTo(expected.getFunctionId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpFunctionsUpdatableFieldsEquals(EmpFunctions expected, EmpFunctions actual) {
        assertThat(actual)
            .as("Verify EmpFunctions relevant properties")
            .satisfies(a -> assertThat(a.getFunctionName()).as("check functionName").isEqualTo(expected.getFunctionName()))
            .satisfies(a -> assertThat(a.getModuleId()).as("check moduleId").isEqualTo(expected.getModuleId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpFunctionsUpdatableRelationshipsEquals(EmpFunctions expected, EmpFunctions actual) {
        // empty method
    }
}
