package com.heavenscode.rac.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

public class EmployeeTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));
    private static final AtomicInteger intCount = new AtomicInteger(random.nextInt() + (2 * Short.MAX_VALUE));

    public static Employee getEmployeeSample1() {
        return new Employee()
            .id(1L)
            .code("code1")
            .fullName("fullName1")
            .nameWithInitials("nameWithInitials1")
            .surname("surname1")
            .nicNumber("nicNumber1")
            .passportNo("passportNo1")
            .age(1)
            .bloodGroup("bloodGroup1")
            .gender("gender1")
            .phone2("phone21")
            .maritalStatus("maritalStatus1")
            .nationality("nationality1")
            .permanentAddress("permanentAddress1")
            .temporaryAddress("temporaryAddress1")
            .home("home1")
            .mobile("mobile1")
            .fax("fax1")
            .email("email1")
            .emergencyContactPerson("emergencyContactPerson1")
            .emergencyNumber("emergencyNumber1")
            .city("city1")
            .district("district1")
            .province("province1")
            .electorate("electorate1")
            .mainRoad("mainRoad1")
            .modeOfTransport("modeOfTransport1")
            .distance("distance1")
            .travelTime("travelTime1")
            .username("username1")
            .password("password1")
            .departmentID(1)
            .departmentCode("departmentCode1")
            .lmu("lmu1")
            .roleId(1)
            .roleName("roleName1")
            .epf("epf1")
            .etf("etf1")
            .designation("designation1")
            .jobStatusId(1)
            .jobStatusName("jobStatusName1")
            .imagePath("imagePath1")
            .bankAccountNo("bankAccountNo1")
            .bankId(1)
            .bankName("bankName1")
            .branchId(1)
            .branchName("branchName1")
            .salaryPaymentBasis("salaryPaymentBasis1")
            .empStatus("empStatus1")
            .religion("religion1")
            .experience("experience1")
            .qualifications("qualifications1")
            .attendanceCode("attendanceCode1");
    }

    public static Employee getEmployeeSample2() {
        return new Employee()
            .id(2L)
            .code("code2")
            .fullName("fullName2")
            .nameWithInitials("nameWithInitials2")
            .surname("surname2")
            .nicNumber("nicNumber2")
            .passportNo("passportNo2")
            .age(2)
            .bloodGroup("bloodGroup2")
            .gender("gender2")
            .phone2("phone22")
            .maritalStatus("maritalStatus2")
            .nationality("nationality2")
            .permanentAddress("permanentAddress2")
            .temporaryAddress("temporaryAddress2")
            .home("home2")
            .mobile("mobile2")
            .fax("fax2")
            .email("email2")
            .emergencyContactPerson("emergencyContactPerson2")
            .emergencyNumber("emergencyNumber2")
            .city("city2")
            .district("district2")
            .province("province2")
            .electorate("electorate2")
            .mainRoad("mainRoad2")
            .modeOfTransport("modeOfTransport2")
            .distance("distance2")
            .travelTime("travelTime2")
            .username("username2")
            .password("password2")
            .departmentID(2)
            .departmentCode("departmentCode2")
            .lmu("lmu2")
            .roleId(2)
            .roleName("roleName2")
            .epf("epf2")
            .etf("etf2")
            .designation("designation2")
            .jobStatusId(2)
            .jobStatusName("jobStatusName2")
            .imagePath("imagePath2")
            .bankAccountNo("bankAccountNo2")
            .bankId(2)
            .bankName("bankName2")
            .branchId(2)
            .branchName("branchName2")
            .salaryPaymentBasis("salaryPaymentBasis2")
            .empStatus("empStatus2")
            .religion("religion2")
            .experience("experience2")
            .qualifications("qualifications2")
            .attendanceCode("attendanceCode2");
    }

    public static Employee getEmployeeRandomSampleGenerator() {
        return new Employee()
            .id(longCount.incrementAndGet())
            .code(UUID.randomUUID().toString())
            .fullName(UUID.randomUUID().toString())
            .nameWithInitials(UUID.randomUUID().toString())
            .surname(UUID.randomUUID().toString())
            .nicNumber(UUID.randomUUID().toString())
            .passportNo(UUID.randomUUID().toString())
            .age(intCount.incrementAndGet())
            .bloodGroup(UUID.randomUUID().toString())
            .gender(UUID.randomUUID().toString())
            .phone2(UUID.randomUUID().toString())
            .maritalStatus(UUID.randomUUID().toString())
            .nationality(UUID.randomUUID().toString())
            .permanentAddress(UUID.randomUUID().toString())
            .temporaryAddress(UUID.randomUUID().toString())
            .home(UUID.randomUUID().toString())
            .mobile(UUID.randomUUID().toString())
            .fax(UUID.randomUUID().toString())
            .email(UUID.randomUUID().toString())
            .emergencyContactPerson(UUID.randomUUID().toString())
            .emergencyNumber(UUID.randomUUID().toString())
            .city(UUID.randomUUID().toString())
            .district(UUID.randomUUID().toString())
            .province(UUID.randomUUID().toString())
            .electorate(UUID.randomUUID().toString())
            .mainRoad(UUID.randomUUID().toString())
            .modeOfTransport(UUID.randomUUID().toString())
            .distance(UUID.randomUUID().toString())
            .travelTime(UUID.randomUUID().toString())
            .username(UUID.randomUUID().toString())
            .password(UUID.randomUUID().toString())
            .departmentID(intCount.incrementAndGet())
            .departmentCode(UUID.randomUUID().toString())
            .lmu(UUID.randomUUID().toString())
            .roleId(intCount.incrementAndGet())
            .roleName(UUID.randomUUID().toString())
            .epf(UUID.randomUUID().toString())
            .etf(UUID.randomUUID().toString())
            .designation(UUID.randomUUID().toString())
            .jobStatusId(intCount.incrementAndGet())
            .jobStatusName(UUID.randomUUID().toString())
            .imagePath(UUID.randomUUID().toString())
            .bankAccountNo(UUID.randomUUID().toString())
            .bankId(intCount.incrementAndGet())
            .bankName(UUID.randomUUID().toString())
            .branchId(intCount.incrementAndGet())
            .branchName(UUID.randomUUID().toString())
            .salaryPaymentBasis(UUID.randomUUID().toString())
            .empStatus(UUID.randomUUID().toString())
            .religion(UUID.randomUUID().toString())
            .experience(UUID.randomUUID().toString())
            .qualifications(UUID.randomUUID().toString())
            .attendanceCode(UUID.randomUUID().toString());
    }
}
