package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmpRolesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRolesAllPropertiesEquals(EmpRoles expected, EmpRoles actual) {
        assertEmpRolesAutoGeneratedPropertiesEquals(expected, actual);
        assertEmpRolesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRolesAllUpdatablePropertiesEquals(EmpRoles expected, EmpRoles actual) {
        assertEmpRolesUpdatableFieldsEquals(expected, actual);
        assertEmpRolesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRolesAutoGeneratedPropertiesEquals(EmpRoles expected, EmpRoles actual) {
        assertThat(actual)
            .as("Verify EmpRoles auto generated properties")
            .satisfies(a -> assertThat(a.getRoleId()).as("check roleId").isEqualTo(expected.getRoleId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRolesUpdatableFieldsEquals(EmpRoles expected, EmpRoles actual) {
        assertThat(actual)
            .as("Verify EmpRoles relevant properties")
            .satisfies(a -> assertThat(a.getRoleName()).as("check roleName").isEqualTo(expected.getRoleName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRolesUpdatableRelationshipsEquals(EmpRoles expected, EmpRoles actual) {
        // empty method
    }
}
