package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmpRoleFunctionPermissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRoleFunctionPermissionAllPropertiesEquals(
        EmpRoleFunctionPermission expected,
        EmpRoleFunctionPermission actual
    ) {
        assertEmpRoleFunctionPermissionAutoGeneratedPropertiesEquals(expected, actual);
        assertEmpRoleFunctionPermissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRoleFunctionPermissionAllUpdatablePropertiesEquals(
        EmpRoleFunctionPermission expected,
        EmpRoleFunctionPermission actual
    ) {
        assertEmpRoleFunctionPermissionUpdatableFieldsEquals(expected, actual);
        assertEmpRoleFunctionPermissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRoleFunctionPermissionAutoGeneratedPropertiesEquals(
        EmpRoleFunctionPermission expected,
        EmpRoleFunctionPermission actual
    ) {
        assertThat(actual)
            .as("Verify EmpRoleFunctionPermission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRoleFunctionPermissionUpdatableFieldsEquals(
        EmpRoleFunctionPermission expected,
        EmpRoleFunctionPermission actual
    ) {
        assertThat(actual)
            .as("Verify EmpRoleFunctionPermission relevant properties")
            .satisfies(a -> assertThat(a.getRoleId()).as("check roleId").isEqualTo(expected.getRoleId()))
            .satisfies(a -> assertThat(a.getFunctionId()).as("check functionId").isEqualTo(expected.getFunctionId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmpRoleFunctionPermissionUpdatableRelationshipsEquals(
        EmpRoleFunctionPermission expected,
        EmpRoleFunctionPermission actual
    ) {
        // empty method
    }
}
