package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SalesInvoiceServiceChargeLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceServiceChargeLineAllPropertiesEquals(
        SalesInvoiceServiceChargeLine expected,
        SalesInvoiceServiceChargeLine actual
    ) {
        assertSalesInvoiceServiceChargeLineAutoGeneratedPropertiesEquals(expected, actual);
        assertSalesInvoiceServiceChargeLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceServiceChargeLineAllUpdatablePropertiesEquals(
        SalesInvoiceServiceChargeLine expected,
        SalesInvoiceServiceChargeLine actual
    ) {
        assertSalesInvoiceServiceChargeLineUpdatableFieldsEquals(expected, actual);
        assertSalesInvoiceServiceChargeLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceServiceChargeLineAutoGeneratedPropertiesEquals(
        SalesInvoiceServiceChargeLine expected,
        SalesInvoiceServiceChargeLine actual
    ) {
        assertThat(expected)
            .as("Verify SalesInvoiceServiceChargeLine auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceServiceChargeLineUpdatableFieldsEquals(
        SalesInvoiceServiceChargeLine expected,
        SalesInvoiceServiceChargeLine actual
    ) {
        assertThat(expected)
            .as("Verify SalesInvoiceServiceChargeLine relevant properties")
            .satisfies(e -> assertThat(e.getInvoiceId()).as("check invoiceId").isEqualTo(actual.getInvoiceId()))
            .satisfies(e -> assertThat(e.getLineId()).as("check lineId").isEqualTo(actual.getLineId()))
            .satisfies(e -> assertThat(e.getOptionId()).as("check optionId").isEqualTo(actual.getOptionId()))
            .satisfies(e -> assertThat(e.getServiceName()).as("check serviceName").isEqualTo(actual.getServiceName()))
            .satisfies(e -> assertThat(e.getServiceDescription()).as("check serviceDescription").isEqualTo(actual.getServiceDescription()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()))
            .satisfies(e -> assertThat(e.getIsCustomerService()).as("check isCustomerService").isEqualTo(actual.getIsCustomerService()))
            .satisfies(e -> assertThat(e.getDiscount()).as("check discount").isEqualTo(actual.getDiscount()))
            .satisfies(e -> assertThat(e.getServicePrice()).as("check servicePrice").isEqualTo(actual.getServicePrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceServiceChargeLineUpdatableRelationshipsEquals(
        SalesInvoiceServiceChargeLine expected,
        SalesInvoiceServiceChargeLine actual
    ) {
        // empty method
    }
}
