package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SaleInvoiceCommonServiceChargeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleInvoiceCommonServiceChargeAllPropertiesEquals(
        SaleInvoiceCommonServiceCharge expected,
        SaleInvoiceCommonServiceCharge actual
    ) {
        assertSaleInvoiceCommonServiceChargeAutoGeneratedPropertiesEquals(expected, actual);
        assertSaleInvoiceCommonServiceChargeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleInvoiceCommonServiceChargeAllUpdatablePropertiesEquals(
        SaleInvoiceCommonServiceCharge expected,
        SaleInvoiceCommonServiceCharge actual
    ) {
        assertSaleInvoiceCommonServiceChargeUpdatableFieldsEquals(expected, actual);
        assertSaleInvoiceCommonServiceChargeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleInvoiceCommonServiceChargeAutoGeneratedPropertiesEquals(
        SaleInvoiceCommonServiceCharge expected,
        SaleInvoiceCommonServiceCharge actual
    ) {
        assertThat(expected)
            .as("Verify SaleInvoiceCommonServiceCharge auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleInvoiceCommonServiceChargeUpdatableFieldsEquals(
        SaleInvoiceCommonServiceCharge expected,
        SaleInvoiceCommonServiceCharge actual
    ) {
        assertThat(expected)
            .as("Verify SaleInvoiceCommonServiceCharge relevant properties")
            .satisfies(e -> assertThat(e.getInvoiceId()).as("check invoiceId").isEqualTo(actual.getInvoiceId()))
            .satisfies(e -> assertThat(e.getLineId()).as("check lineId").isEqualTo(actual.getLineId()))
            .satisfies(e -> assertThat(e.getOptionId()).as("check optionId").isEqualTo(actual.getOptionId()))
            .satisfies(e -> assertThat(e.getMainId()).as("check mainId").isEqualTo(actual.getMainId()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()))
            .satisfies(e -> assertThat(e.getDiscount()).as("check discount").isEqualTo(actual.getDiscount()))
            .satisfies(e -> assertThat(e.getServicePrice()).as("check servicePrice").isEqualTo(actual.getServicePrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSaleInvoiceCommonServiceChargeUpdatableRelationshipsEquals(
        SaleInvoiceCommonServiceCharge expected,
        SaleInvoiceCommonServiceCharge actual
    ) {
        // empty method
    }
}
