package com.heavenscode.rac.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SalesInvoiceLinesDummyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceLinesDummyAllPropertiesEquals(SalesInvoiceLinesDummy expected, SalesInvoiceLinesDummy actual) {
        assertSalesInvoiceLinesDummyAutoGeneratedPropertiesEquals(expected, actual);
        assertSalesInvoiceLinesDummyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceLinesDummyAllUpdatablePropertiesEquals(
        SalesInvoiceLinesDummy expected,
        SalesInvoiceLinesDummy actual
    ) {
        assertSalesInvoiceLinesDummyUpdatableFieldsEquals(expected, actual);
        assertSalesInvoiceLinesDummyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceLinesDummyAutoGeneratedPropertiesEquals(
        SalesInvoiceLinesDummy expected,
        SalesInvoiceLinesDummy actual
    ) {
        assertThat(expected)
            .as("Verify SalesInvoiceLinesDummy auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceLinesDummyUpdatableFieldsEquals(SalesInvoiceLinesDummy expected, SalesInvoiceLinesDummy actual) {
        assertThat(expected)
            .as("Verify SalesInvoiceLinesDummy relevant properties")
            .satisfies(e -> assertThat(e.getInvoiceId()).as("check invoiceId").isEqualTo(actual.getInvoiceId()))
            .satisfies(e -> assertThat(e.getLineId()).as("check lineId").isEqualTo(actual.getLineId()))
            .satisfies(e -> assertThat(e.getItemId()).as("check itemId").isEqualTo(actual.getItemId()))
            .satisfies(e -> assertThat(e.getItemCode()).as("check itemCode").isEqualTo(actual.getItemCode()))
            .satisfies(e -> assertThat(e.getItemName()).as("check itemName").isEqualTo(actual.getItemName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getUnitOfMeasurement()).as("check unitOfMeasurement").isEqualTo(actual.getUnitOfMeasurement()))
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getItemCost()).as("check itemCost").isEqualTo(actual.getItemCost()))
            .satisfies(e -> assertThat(e.getItemPrice()).as("check itemPrice").isEqualTo(actual.getItemPrice()))
            .satisfies(e -> assertThat(e.getDiscount()).as("check discount").isEqualTo(actual.getDiscount()))
            .satisfies(e -> assertThat(e.getTax()).as("check tax").isEqualTo(actual.getTax()))
            .satisfies(e -> assertThat(e.getSellingPrice()).as("check sellingPrice").isEqualTo(actual.getSellingPrice()))
            .satisfies(e -> assertThat(e.getLineTotal()).as("check lineTotal").isEqualTo(actual.getLineTotal()))
            .satisfies(e -> assertThat(e.getLmu()).as("check lmu").isEqualTo(actual.getLmu()))
            .satisfies(e -> assertThat(e.getLmd()).as("check lmd").isEqualTo(actual.getLmd()))
            .satisfies(e -> assertThat(e.getNbt()).as("check nbt").isEqualTo(actual.getNbt()))
            .satisfies(e -> assertThat(e.getVat()).as("check vat").isEqualTo(actual.getVat()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalesInvoiceLinesDummyUpdatableRelationshipsEquals(
        SalesInvoiceLinesDummy expected,
        SalesInvoiceLinesDummy actual
    ) {
        // empty method
    }
}
