# app.yml
name: rac
services:
  app:
    image: rac
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      #- SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1438;database=OziErpWebRathnaweeraService;encrypt=false;trustServerCertificate=true
      #- SPRING_LIQUIBASE_URL=jdbc:sqlserver://mssql:1438;database=OziErpWebRathnaweeraService;encrypt=false;trustServerCertificate=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://rac-mssql-1:1438;databaseName=RACTestDB;encrypt=false;trustServerCertificate=true
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://rac-mssql-1:1438;databaseName=RACTestDB;encrypt=false;trustServerCertificate=true
      #- SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=RACTestDB;encrypt=false;trustServerCertificate=true
      #- SPRING_LIQUIBASE_URL=jdbc:sqlserver://mssql:1433;databaseName=RACTestDB;encrypt=false;trustServerCertificate=true

      - SPRING_DATASOURCE_USERNAME=sa
      #- SPRING_DATASOURCE_PASSWORD=YourStrong!Passw0rd
      - SPRING_DATASOURCE_PASSWORD=december99
      - SPRING_LIQUIBASE_ENABLED=false

    ports:
      - 127.0.0.1:8085:8080

    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40

    depends_on:
      mssql:
        condition: service_healthy

  mssql:
    extends:
      file: ./mssql.yml
      service: mssql
