import dayjs from 'dayjs/esm';

import { ICustomer, NewCustomer } from './customer.model';

export const sampleWithRequiredData: ICustomer = {
  id: 3366,
};

export const sampleWithPartialData: ICustomer = {
  id: 15772,
  fullname: 'uselessly mild likewise',
  callingname: 'however whenever naughty',
  gender: 'instead',
  maritalstatus: 'gadzooks',
  marrieddate: dayjs('2024-08-13'),
  nationality: 9305,
  territory: 'smooth minus',
  team: 'shred huzzah vivacious',
  businessregdate: dayjs('2024-08-14'),
  residencehouseno: 'mid advocate truly',
  businessdistrictid: 2463,
  contactpersonphone: 'frugal gape wide',
  contactpersonmobile: 'ouch when ew',
  isinternalcustomer: 6521,
  description: 'from order',
  lmu: 12335,
  lmd: dayjs('2024-08-14T09:44'),
  maximumdiscount: 3586.35,
  hassecuritydeposit: false,
  cashpaymentbeforeload: true,
  cashlastinvoicebeforeload: false,
  creditoneweekcheck: false,
  hassecuritydepositbond: true,
  hasassestsdeposit: false,
  employeraddress: 'of stump',
  previousindustry: 'worst versus',
  lon: 'than widow save',
};

export const sampleWithFullData: ICustomer = {
  id: 4149,
  customertype: 21252,
  code: 'commandeer',
  title: 'bah',
  namewithinitials: 'indeed astride outlandish',
  fullname: 'pantyhose',
  callingname: 'pro',
  nicno: 'phew devoted',
  nicissueddate: dayjs('2024-08-13'),
  dateofbirth: dayjs('2024-08-13'),
  bloodgroup: 'ew',
  gender: 'but sharply candid',
  maritalstatus: 'after',
  marrieddate: dayjs('2024-08-13'),
  nationality: 28763,
  territory: 'insignificant lest and',
  religion: 11219,
  team: 'indeed oof',
  businessname: 'uneven aside uh-huh',
  businessregdate: dayjs('2024-08-14'),
  businessregno: 'now fortunate',
  profilepicturepath: 'fencing',
  residencehouseno: 'officially',
  residenceaddress: 'another oh',
  residencecity: 'collectivization cautiously yahoo',
  residencephone: 'ack',
  businesslocationno: 'for circa sonnet',
  businessaddress: 'quaff beside pressure',
  businesscity: 'blond off orderly',
  businessphone1: 'eggplant expatiate',
  businessphone2: 'squiggly rapidly sympathetically',
  businessmobile: 'presell wholly',
  businessfax: 'casement',
  businessemail: 'whoever when',
  businessprovinceid: 27982,
  businessdistrictid: 8849,
  contactpersonname: 'at wisecrack handful',
  contactpersonphone: 'duster',
  contactpersonmobile: 'debit quirkily upon',
  contactpersonemail: 'loyally handle wearily',
  rootmappath: 'furthermore',
  website: 'phooey as commodity',
  registrationdate: dayjs('2024-08-14T06:33'),
  isactive: 2787,
  isinternalcustomer: 505,
  description: 'extent qua',
  lmu: 25815,
  lmd: dayjs('2024-08-13T19:54'),
  maximumdiscount: 13783.94,
  creditlimit: 27281.47,
  hassecuritydeposit: true,
  securitydepositamount: 11607.63,
  paybycash: false,
  cashpaymentbeforeload: true,
  cashlastinvoicebeforeload: true,
  paybycredit: false,
  creditoneweekcheck: true,
  creditpaymentbydays: 29339,
  haspurchasingdeposit: false,
  hassecuritydepositbond: false,
  hasassestsdeposit: true,
  customerrootmappath: 'till tousle',
  employername: 'opposite',
  employeraddress: 'afraid',
  employerphone: 'pace boohoo',
  employerdesignation: 'serve boohoo',
  previousemployername: 'mortally alongside concerning',
  previousemployeraddress: 'miskey',
  previousindustry: 'so wrongly',
  previousperiod: 'than till',
  previouspositions: 'aw plagiarise pity',
  previousresionforleaving: 'finger spork elegant',
  hascreaditlimit: true,
  accountid: 1186,
  accountcode: 'youthfully pull stranger',
  isregistered: false,
  vatregnumber: 'daintily',
  tinnumber: 'officially only',
  lat: 'wherever',
  lon: 'fork putrefy why',
  creditperiod: 11901,
};

export const sampleWithNewData: NewCustomer = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
