import dayjs from 'dayjs/esm';

import { IEmployee, NewEmployee } from './employee.model';

export const sampleWithRequiredData: IEmployee = {
  id: 8098,
};

export const sampleWithPartialData: IEmployee = {
  id: 26781,
  passportNo: 'down eek cheese',
  passportIssueDate: dayjs('2025-03-05'),
  passportExpDate: dayjs('2025-03-05'),
  dateOfBirth: dayjs('2025-03-05'),
  bloodGroup: 'officially',
  gender: 'requite once',
  nationality: 'sign grim highlight',
  permanentAddress: 'emphasize',
  home: 'shabby whenever',
  emergencyContactPerson: 'hastily',
  city: 'Oak Park',
  modeOfTransport: 'attest unless continually',
  distance: 'unlined warp',
  username: 'actually likewise teriyaki',
  password: 'mechanically',
  departmentID: 29741,
  roleName: 'wetly scram',
  epf: 'contravene once whispered',
  etf: 'parody pish',
  designation: 'blah pfft',
  jobStatusId: 10772,
  bankId: 10482,
  bankName: 'yet lest',
  religion: 'whereas mysteriously correctly',
  experience: 'turret',
  qualifications: 'yahoo',
};

export const sampleWithFullData: IEmployee = {
  id: 30668,
  code: 'bank disinherit',
  fullName: 'yuck anenst save',
  nameWithInitials: 'per alongside analogy',
  surname: 'mmm reckless',
  nicNumber: 'kindly brr',
  nicIssueDate: dayjs('2025-03-05'),
  passportNo: 'amused glum',
  passportIssueDate: dayjs('2025-03-05'),
  passportExpDate: dayjs('2025-03-05'),
  dateOfBirth: dayjs('2025-03-05'),
  age: 31688,
  bloodGroup: 'up whole',
  gender: 'not underplay quit',
  phone2: 'expensive',
  maritalStatus: 'availability',
  marriedDate: dayjs('2025-03-06'),
  nationality: 'calmly',
  permanentAddress: 'ha',
  temporaryAddress: 'design beneath',
  home: 'unlike',
  mobile: 'athwart',
  fax: 'kettledrum only warming',
  email: 'Jettie1@gmail.com',
  emergencyContactPerson: 'lovely see',
  emergencyNumber: 'stall',
  city: 'Amarillo',
  district: 'well to',
  province: 'yahoo liberalize pish',
  electorate: 'finally among',
  mainRoad: 'finally',
  modeOfTransport: 'ouch as for',
  distance: 'joyfully',
  travelTime: 'instructor squeaky',
  username: 'accessorise',
  password: 'however throughout think',
  departmentID: 25723,
  departmentCode: 'questioningly criminal starch',
  empRegDate: dayjs('2025-03-06'),
  lmu: 'during everlasting',
  lmd: dayjs('2025-03-05T13:48'),
  roleId: 5342,
  roleName: 'gadzooks',
  epf: 'fort',
  etf: 'cute exonerate hm',
  dateJoined: dayjs('2025-03-06T09:17'),
  dateResigned: dayjs('2025-03-06T12:58'),
  designation: 'throughout pfft',
  jobStatusId: 19427,
  jobStatusName: 'other truly',
  imagePath: 'boo',
  bankAccountNo: 'innocently westernize',
  bankId: 25099,
  bankName: 'taut ah woot',
  branchId: 8987,
  branchName: 'mantua innocently',
  salaryPaymentBasis: 'yet ugh',
  empStatus: 'aw since',
  religion: 'whereas giant',
  experience: 'circa',
  qualifications: 'manner',
  attendanceCode: 'fooey notarize fledgling',
  isActive: false,
};

export const sampleWithNewData: NewEmployee = {
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
